name: Deploy Ticket API Service

on:
  push:
    branches:
      - main
    paths:
      - 'server/**' # Trigger only when backend changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd server
          npm install

      - name: Build (if applicable)
        run: |
          cd server
          npm run build || echo "No build step defined"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ticket-api-service
          slot-name: production
          package: ./server
